Models/ErrorViewModel.cs
namespace APOD.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MediaType.cs
namespace APOD.Models
{
    public enum MediaType
    {
        Video = 0,
        image = 1,
    }
}

Models/NasaApod.cs
namespace APOD.Models
{
    public class NasaApod
    {
        public string Copyright { get; set; }
        public string Date { get; set; }
        public string Explanation { get; set; }
        public string HdUrl { get; set; }
        public MediaType media_type { get; set; }
        public string service_version { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public byte[] Image { get; set; }

        //public NasaApod(){}

        public NasaApod(string copyright, string date, string explanation, string hdUrl, string media_type, string serviceVersion, string title, string url, byte[] image)
        {
            this.Copyright = copyright;
            this.Date = date;
            this.Explanation = explanation;
            this.HdUrl = hdUrl;
            this.media_type = media_type.Equals("Video") ? MediaType.Video : MediaType.image;
            this.service_version = serviceVersion;
            this.Title = title;
            this.Url = url;
            this.Image = image;

            
            
        }
    }
}

Controllers/ApodController.cs
using APOD.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;


namespace APOD.Controllers
{
    public class ApodController : Controller
    {
        private string _apiKey = "Xfwoi46lbj0tkkjmDrGt0f9uappcLhMjQhwDk0Mf";
        private string _apodEndpoint = "https://api.nasa.gov/planetary/apod";
        
        
       //https://localhost:7129/APOD/Get
        [HttpPost]
        public IActionResult Get(string date)
        {
            bool isHd = false;

            var data = Convert.ToDateTime(date);
            string endpoint = $"{_apodEndpoint}?api_key={_apiKey}&hd={isHd.ToString().ToLower()}&date={data.ToString("yyyy-MM-dd")}";
            using (var client = new HttpClient(new HttpClientHandler()))
            {
                var result = client.GetAsync(endpoint);

                var resultToObject = result.Result.Content.ReadAsStringAsync();

                var deserialized = JsonConvert.DeserializeObject<NasaApod>(resultToObject.Result);

                if (deserialized != null && deserialized.media_type == MediaType.Video)
                {
                    return View("GetVideo", deserialized);

                }

                return View("GetPhoto", deserialized);
            }
        }
    }
}

Controllers/HomeController.cs
using APOD.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace APOD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

    }
}

Views/APOD/GetPhoto.cshtml
@model APOD.Models.NasaApod

@{
    ViewData["title"] = "GetPhoto";
}

<style>
    #image_container
    {
        width: 500px; 
        height: 500px; 
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
    img {
        max-width: 100%;
        object-fit: contain;
        
    }
</style>


<div class="text-center">
    <h2 class="display-4">Here you go! The picture you requested! Enjoy :)</h2>
    <br />

    <h3> @Model.Title</h3>
    
    <div id="image_container">
        <img src=@Model.HdUrl>
    </div>

    <br />
    <p>And if you are even more curious and you want to know what are you in fact looking at, here's an explanation for ya:</p><br/>
    <p>@Model.Explanation</p>

</div>

Views/APOD/GetVideo.cshtml
@model APOD.Models.NasaApod

@{
    ViewData["title"] = "GetVideo";
}

<div class="text-center">
    <h2 class="display-4">Here you go! The picture you requested! Enjoy :)</h2>
    <br />

    <h3> @Model.Title</h3>

    <div>
        <iframe width="480" height="853" src=@Model.Url title=@Model.Title frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
    </div>

    <br />
    <h3> And if you are even more curious and you want to know what are you in fact looking at, here's an explanation for ya:</h3>
    <p>@Model.Explanation</p>

</div>

Views/APOD/Index.cshtml
@{
    ViewData["title"] = "Index";
}

<h1>Index</h1>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p> Nothing to see here, sorry :( </p>

</div>

Views/Home/Index.cshtml
@{
    ViewData["title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p> Hello! If you came here it means you are a huge astronomy fan, and you would like to see 
        today's  or any other day's astronomy photo or video, depending on your luck. 
        So go on, enter the date you want to see a picture from! </p>

    
    @using (Html.BeginForm("Get", "Apod", FormMethod.Post))
    {
        <p>Insert a valid date in the following format: YYYY-MM-DD </p>
        @Html.TextBox("date")
        <input type="submit" value="Submit" />
    }

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["title"] - APOD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/APOD.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">APOD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - APOD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>